import { defineConfig } from "tsdown";
import vue from "@vitejs/plugin-vue";

export default defineConfig({
    entry: ["src/index.ts"],
    format: ["esm", "cjs"],
    // DTS is generated by vue-tsc via the `build:dts` script, not by tsdown,
    // because rolldown-plugin-dts cannot process Vue SFCs.
    dts: false,
    clean: true,
    plugins: [vue()],
    external: ["vue"],
    sourcemap: true,
    copy: [{ from: "src/styles", to: "styles" }],
});
